### ISSUE TITLE
Meh

### ISSUE THREAD

**Issue by Martum** [SAMSistemas/timesheet#1]
Somos conscientes que bien podría venderle esto a la competencia, no?

**Comment by Martum** [comment]
Si W viese que usan un repo externo, y PUBLICO!!

**Comment by JonatanSalas** [comment]
jajajaja se pondria loca loca W

Enviado por Outlook para Android

On Mon, Nov 2, 2015 at 5:20 PM -0800, "Martín Montenegro" notifications@github.com wrote:
Si W viese que usan un repo externo, y PUBLICO!!

---

**Comment by Martum** [comment]
jajaja W is always watching!

**Comment by JonatanSalas** [comment]
He is like god. Jajajajaja Che mi libreria tuvo exito, si LIBRERIA.. la palabra que tanto amas muajajaja

Enviado por Outlook para Android

On Mon, Nov 2, 2015 at 5:23 PM -0800, "Martín Montenegro" notifications@github.com wrote:
jajaja W is always watching!

---

**Comment by Martum** [comment]
jajajajaj menos mal que la descripcion es en ingles y no en español entonce!

**Comment by JonatanSalas** [comment]
jajajaja si es en Español estoy al horno.. En vez de + starred, - starred jajaja

Enviado por Outlook para Android

On Mon, Nov 2, 2015 at 5:29 PM -0800, "Martín Montenegro" notifications@github.com wrote:
jajajajaj menos mal que la descripcion es en ingles y no en español entonce!

---
